# Generated by Django 2.2.3 on 2019-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentmodel',
            name='author',
            field=models.TextField(default='sanchit', max_length=100),
        ),
        migrations.AddField(
            model_name='entertainmentmodel',
            name='jumbotron',
            field=models.FileField(default='no image', upload_to=''),
        ),
    ]
