# Generated by Django 2.2.3 on 2019-08-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190828_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='jumbotron',
            field=models.ImageField(default='no image', upload_to='media/'),
        ),
    ]
