# Generated by Django 2.2.3 on 2019-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190828_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentmodel',
            name='source',
            field=models.URLField(default='Not available'),
        ),
    ]
